version: '3'

volumes:
  postgres_data:
  # src:
  media:
  static:
  logs:

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web1
      - web2

  db:
    image: postgres:13-alpine
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - PGUSER=user
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=midterm
    ports:
      - "5432:5432"

  web1:
    build: .
    command: >
      bash -c "python3 manage.py migrate && python manage.py collectstatic --noinput && python manage.py makemessages -l ru && python manage.py compilemessages && gunicorn config.wsgi:application --bind 0.0.0.0:8001 --workers 1 --log-level 'debug'"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # - .:/src
      - ./media:/src/mediafiles
      - ./static:/src/static
      - logs:/logs
    depends_on:
      - db

  web2:
    build: .
    command: >
      bash -c "python3 manage.py migrate && python manage.py collectstatic --noinput && python manage.py makemessages -l ru && python manage.py compilemessages && gunicorn config.wsgi:application --bind 0.0.0.0:8001 --workers 1 --log-level 'debug'"
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      # - .:/src
      - ./media:/src/mediafiles
      - ./static:/src/static
      - logs:/logs
    depends_on:
      - db

  redis:
    restart: unless-stopped
    image: redis:alpine
    command: redis-server --requirepass OMeDuTERnUtH
    ports:
      - "6380:6379"

  celery:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    command: celery -A config worker -l info
    # volumes:
      # - .:/src
      # - media:/mediafiles
    depends_on:
      - redis
#
#  celery-beat:
#    build: .
#    restart: unless-stopped
#    env_file:
#      - .env
#    command: celery -A config beat -l debug
#    # volumes:
#      # - .:/src
#      # - media:/mediafiles
#    depends_on:
#      - redis
