# Generated by Django 5.0.7 on 2024-10-02 12:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track_number', models.CharField(max_length=255, null=True, unique=True)),
                ('currency', models.CharField(choices=[('kzt', 'kzt'), ('rub', 'rub'), ('usd', 'usd'), ('cny', 'cny')], default='usd')),
                ('comment', models.CharField(max_length=255, null=True)),
                ('status', models.CharField(choices=[('introduced', 'Введен'), ('at_warehouse', 'На складе'), ('on_the_way', 'В пути'), ('at_pickup_point', 'В ПВЗ'), ('given', 'Получен'), ('waiting_for_payment', 'Ожидает оплаты'), ('paid', 'Оплачено')], default='introduced')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('shipping_price', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('code', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('comment', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('introduced', 'Введен'), ('at_warehouse', 'На складе'), ('on_the_way', 'В пути'), ('at_pickup_point', 'В ПВЗ'), ('given', 'Получен'), ('waiting_for_payment', 'Ожидает оплаты'), ('paid', 'Оплачено')], max_length=50)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
