# Generated by Django 5.0.7 on 2024-10-02 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        ('pickup_point', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='pickup_point.cell'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pickup_point.pickuppoint'),
        ),
    ]
