# Generated by Django 5.0.7 on 2024-10-02 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(max_length=9, unique=True)),
                ('date_of_issue', models.DateField()),
                ('validity_period', models.DateField()),
                ('iin', models.CharField(max_length=12, unique=True)),
                ('given_by', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MyAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.city')),
            ],
        ),
    ]
