# Generated by Django 5.0.7 on 2024-10-02 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
        ('personal_info', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myaddress',
            name='mobile_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='my_addresses', to='users.mobileuser'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='citizenship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.country'),
        ),
        migrations.AddField(
            model_name='personalinfo',
            name='mobile_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info', to='users.mobileuser'),
        ),
    ]
