# Generated by Django 5.0.7 on 2024-10-07 08:14

import apps.users.avatars.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=apps.users.avatars.models.avatar_upload)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='mobileuser',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.avatar'),
        ),
    ]
