# Generated by Django 5.0.7 on 2024-10-07 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avatars', '0001_initial'),
        ('users', '0002_avatar_mobileuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobileuser',
            name='avatar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='avatars.avatar'),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
