# Generated by Django 5.0.7 on 2024-10-02 12:23

import apps.pickup_point.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_full', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cell_number', models.PositiveIntegerField()),
                ('max_orders', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PickUpPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('full_name', models.CharField(max_length=255)),
                ('juridical_form', models.CharField(choices=[('TOO', 'TOO'), ('ИП', 'ИП')], max_length=20)),
                ('individual_identification_number', models.FileField(upload_to=apps.pickup_point.models.individual_identification_number_upload)),
                ('online_banking_certificate', models.FileField(upload_to=apps.pickup_point.models.online_banking_certificate_upload)),
                ('nds_payer', models.BooleanField()),
                ('nds_payer_certificate', models.FileField(null=True, upload_to=apps.pickup_point.models.nds_payer_certificate_upload)),
                ('cells_in_stock', models.IntegerField()),
                ('status', models.CharField(choices=[('inactive', 'inactive'), ('active', 'active'), ('in_review', 'in_review')], default='inactive')),
            ],
        ),
    ]
