# Generated by Django 5.0.7 on 2024-10-02 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
        ('pickup_point', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.mobileuser'),
        ),
        migrations.AddField(
            model_name='pickuppoint',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.city'),
        ),
        migrations.AddField(
            model_name='cell',
            name='pickup_point',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='pickup_point.pickuppoint'),
        ),
    ]
