# Generated by Django 5.0.7 on 2024-10-07 09:19

import apps.users.avatars.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=apps.users.avatars.models.avatar_upload)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
