# Generated by Django 5.0.7 on 2024-10-02 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Dropshipping', 'dropshipping'), ('Sorting', 'sorting'), ('Distribution', 'distribution')], default='warehouse')),
                ('can_evaluate_order', models.BooleanField(default=False)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.city')),
            ],
        ),
        migrations.CreateModel(
            name='Tare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_full', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('max_orders', models.PositiveIntegerField()),
                ('tare_number', models.PositiveIntegerField()),
                ('warehouse', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tare', to='warehouse.warehouse')),
            ],
        ),
    ]
